# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Simonwehle < Formula
  desc ""
  homepage "https://github.com/simonwehle/yt2abs"
  version "1.5.3"

  on_macos do
    url "https://github.com/simonwehle/yt2abs/releases/download/v1.5.3/yt2abs_1.5.3_darwin_all.tar.gz"
    sha256 "e681b81c511407058602dadfd960b501be1cc17e390406359aa5f764db0ab6ad"

    def install
      bin.install "yt2abs"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/simonwehle/yt2abs/releases/download/v1.5.3/yt2abs_1.5.3_linux_amd64.tar.gz"
      sha256 "3f70ba20a90f3e9bcf7574f78a52c1a2d403ef569b979837af6411b951e850f3"

      def install
        bin.install "yt2abs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonwehle/yt2abs/releases/download/v1.5.3/yt2abs_1.5.3_linux_arm64.tar.gz"
      sha256 "e65d648ece9c8149963a6597d0b20a8f8d6a24af04f4a7fbe6bc34f881c20624"

      def install
        bin.install "yt2abs"
      end
    end
  end
end
