# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yt2abs < Formula
  desc ""
  homepage "https://github.com/simonwehle/yt2abs"
  version "1.7.0"

  on_macos do
    url "https://github.com/simonwehle/yt2abs/releases/download/v1.7.0/yt2abs_1.7.0_darwin_all.tar.gz"
    sha256 "a49f9ff6f0f44b04f76b6cda3e49844c8fa76400478aecedf03b359ce64b6090"

    def install
      bin.install "yt2abs"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/simonwehle/yt2abs/releases/download/v1.7.0/yt2abs_1.7.0_linux_amd64.tar.gz"
      sha256 "5a589521690f0ffd4f99310a52f77bc179b1a3be856e7c9490d91f5b4da5d7ec"

      def install
        bin.install "yt2abs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonwehle/yt2abs/releases/download/v1.7.0/yt2abs_1.7.0_linux_arm64.tar.gz"
      sha256 "32f194a1ea6722cfccf110abadd353e27fa762f4a5a83696bd1752c78cca6837"

      def install
        bin.install "yt2abs"
      end
    end
  end
end
