# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yt2abs < Formula
  desc ""
  homepage "https://github.com/simonwehle/yt2abs"
  version "1.7.5"

  on_macos do
    url "https://github.com/simonwehle/yt2abs/releases/download/v1.7.5/yt2abs_1.7.5_darwin_all.tar.gz"
    sha256 "ba7a4899eadc9b5553762c8f01d9b78b739a34c57fe8c9d7ccaa8f9f633b9955"

    def install
      bin.install "yt2abs"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/simonwehle/yt2abs/releases/download/v1.7.5/yt2abs_1.7.5_linux_amd64.tar.gz"
      sha256 "de142f93822cb972ecf5f00b906bf0cb3510a44a45a4ebaddce5af54d6597538"

      def install
        bin.install "yt2abs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/simonwehle/yt2abs/releases/download/v1.7.5/yt2abs_1.7.5_linux_arm64.tar.gz"
      sha256 "b7935589bec5a385e6471b39caa8c06068c8726be5d6a9e85e1fafdf8171d0ed"

      def install
        bin.install "yt2abs"
      end
    end
  end
end
